"""followers

Revision ID: 141fd38b87bf
Revises: f7d84e07c508
Create Date: 2019-11-05 10:10:27.647318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141fd38b87bf'
down_revision = 'f7d84e07c508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
